# Generated by Django 5.1.6 on 2025-03-26 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_userdetails_weight'),
        ('workouts', '0002_remove_userworkouthistory_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workouthistory',
            options={},
        ),
        migrations.AddField(
            model_name='workouthistory',
            name='video_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='workouthistory',
            index=models.Index(fields=['user', 'workout_date'], name='workouts_wo_user_id_786a10_idx'),
        ),
    ]
