# Generated by Django 5.1.6 on 2025-03-22 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0011_workout_week_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('video_url', models.URLField(blank=True, null=True)),
                ('goal', models.CharField(max_length=50)),
                ('training_level', models.CharField(max_length=50)),
                ('min_weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_weight', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.DeleteModel(
            name='Workout',
        ),
    ]
