# Generated by Django 5.1.6 on 2025-03-25 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0012_workoutvideo_delete_workout'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('video_url', models.URLField(blank=True, null=True)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='workouts/')),
                ('goal', models.CharField(max_length=50)),
                ('training_level', models.CharField(max_length=50)),
                ('min_weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('repeat_interval_weeks', models.IntegerField()),
                ('repeat_days', models.JSONField(default=list)),
                ('week_number', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='WorkoutVideo',
        ),
    ]
