# Generated by Django 5.1.6 on 2025-03-26 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0013_workout_delete_workoutvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='is_ai_generated',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
